#!/usr/bin/env bash

alias ls='ls -GF'
alias ll='ls -hlGFa'

alias pu='pushd $(pwd)'
alias po='popd'
alias dirs='dirs -v'

alias drccall='cd www/ && drush cc all && cd ..'

# TODO make alias 'fame' in .gitconfig when '\.php' matching is not hardcoded.
alias gfame='git  ls-tree -r HEAD | cut -f 2 | grep -E '\.php$' | xargs -n1 git blame --line-porcelain | grep "^author " | sort | uniq -c | sort -nr | sed  "s/ author//"'

# find the 10 largest files in the current directory
alias flarge='find . -type f -print0 | xargs -0 du -s | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'

# Use fzf to generate a link to a file in the S3 bucket 'yermama'
alias ym='~/bin/ym $(aws ls -1 yermama | fzf) | pbcopy'

# TODO days => hours [=> minutes [=> seconds]]
# TODO configurable dates?
alias daystill="python -c 'from datetime import date; print \"Nog %sX slapen.\" % (date(2019,3,1) - date.today()).days'"

alias t=tmux_attach
alias w=goto_project
alias e=mvim

# Generate ctags file for Vim in a Drupal 7 project.
# For Drupal 8 and other PHP project using composer (and Git), PHPhactor works
# just fine.
alias generate_tags='ctags --langmap=php:.engine.inc.module.theme.install.php --php-kinds=cdfi --languages=php --recurse --fields=+l'
