#!/usr/bin/env bash

alias ls='ls -GF'
alias ll='ls -hlGFa'

alias pu='pushd $(pwd)'
alias po='popd'
alias dirs='dirs -v'

alias drccall='cd www/ && drush cc all && cd ..'

# TODO make alias 'fame' in .gitconfig when '\.php' matching is not hardcoded.
alias gfame='git  ls-tree -r HEAD | cut -f 2 | grep -E '\.php$' | xargs -n1 git blame --line-porcelain | grep "^author " | sort | uniq -c | sort -nr | sed  "s/ author//"'

# find the 10 largest files in the current directory
alias flarge='find . -type f -print0 | xargs -0 du -s | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'

# Use fzf to generate a link to a file in the S3 bucket 'yermama'
alias ym='~/bin/ym $(aws ls -1 yermama | fzf) | pbcopy'

# TODO days => hours [=> minutes [=> seconds]]
# TODO configurable dates?
alias daystill="python -c 'from datetime import date; print \"Nog %sX slapen.\" % (date(2019,3,1) - date.today()).days'"

# When ssh'ing into a server, the window title and the tab title are changed to
# the ssh server and user etc... but when logging out of the server, the tab and
# window do not restore.  This alias does that.
# "Default" is the name of the default iTerm2 profile.
# TODO Replace "Default" with the actual profile name if possible.
alias restoretitle="echo -ne \"\e]1;Default\a\""
