#!/usr/bin/env bash

#
# Setup bash completions for different tools.
# Note that .bash/functions must be sourced before this file because we use
# ssh_load_autocomplete here.
#
# Tip:
# If an alias was defined for a command, completions for that command will not
# work with the defined alias.
# But completion can be configured for that alias, for example:
# Supposing `alias g=git` one can do:
#
#   complete -o default -o nospace -F _git g
#


#
# adds ~/.ssh/config to the ssh autocomplete
# Call whenever ssh host config changes (@see ssh_configure_host)
#
ssh_load_autocomplete() {
    complete -W "$(awk '/^\s*Host\s*/ { sub(/^\s*Host /, ""); print; }' ~/.ssh/{config,digipolis-hosts})" ssh uli ssh_drush ssh_user
}


complete -o default -o nospace -F _git g

homebrew_completions=/usr/local/etc/bash_completion.d
for each in $(ls $homebrew_completions); do
    # These are symlinks, so the "@" is removed.
    fn="${each%@}"

    # Completions for the Silver Searchers screw up Bash's path completion.
    if [[ "$fn" != "ag.bashcomp.sh" ]]; then
        source "$homebrew_completions/$fn"
    fi
done

# FZF
# TODO split up? (because it does more than completion)
#      Or move it to separate fzf file (as to not have 1 tool config spread
#      over 3 files)
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
  export PATH="$PATH:/usr/local/opt/fzf/bin"
fi
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.bash" 2> /dev/null
source "/usr/local/opt/fzf/shell/key-bindings.bash"
export FZF_DEFAULT_OPTS='--color=dark'

ssh_load_autocomplete
