#!/usr/bin/env bash

#
# Bash configuration
# PATH, var exports, vars used in .bash/ system, ...
#

#
# Path, keep at 1 line per added directory.
# This makes it more readable and easier to edit later.
#
PATH="/usr/local/mysql/bin:$PATH"
PATH="/usr/local/opt/sqlite/bin:$PATH"
PATH="/Volumes/webdev/www/_apache/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="$HOME/.composer/vendor/bin:$PATH"
PATH="$HOME/bin:$PATH"
export PATH

export EDITOR=nvim
export GIT_EDITOR="$EDITOR"

# More common command history, trying not to have duplicates.
export HISTCONTROL=ignoreboth
shopt -s histappend

# Keep a lot of history
export HISTFILESIZE=10000000
export HISTSIZE=1000000

# Track when which command was executed
export HISTTIMEFORMAT="%Y-%m-%d %T "

export LIQUIBASE_HOME=/usr/local/opt/liquibase/libexec

#
# Personal config
#

# Where are projects checked out?
# No trailing slash!
export DIR_PROJECTS=$HOME/Projects

# Where are the various file templates (.gitignore, .editorconfig, ...)
# No trailing slash!
export DIR_TEMPLATES=$HOME/templates

#
# Which commands.
#

# For Mac OSX: use gsed if available.
export SED=$(command -v gsed) || $(command -v sed)

# Default FZF preview mode (see tpl() and goto_project() in .bash/function)
export FZF_PREVIEW='fzf-tmux --preview-window right:60% --preview'

export LANG="en_US.UTF-8"

# If cowsay is installed, Ansible will use it by default.
# Although fun, it does not make up for the loss in screen space.
export ANSIBLE_NOCOWS=1
