#!/usr/bin/env bash

#
# Bash configuration
# PATH, var exports, vars used in .bash/ system, ...
#

#
# Path and environment vars.
#
export PATH="/usr/local/php5/bin:$HOME/bin:$HOME/.composer/vendor/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/opt/sqlite/bin:$PATH"
export EDITOR=nvim
export GIT_EDITOR="$EDITOR"

# More common command history, trying not to have duplicates.
export HISTCONTROL=ignoreboth
shopt -s histappend
export HISTFILESIZE=10000000
export HISTSIZE=1000000

export LIQUIBASE_HOME=/usr/local/opt/liquibase/libexec

#
# Personal config
#

# Where are projects checked out?
# No trailing slash!
export DIR_PROJECTS=$HOME/Projects

# Where are the various file templates (.gitignore, .editorconfig, ...)
export DIR_TEMPLATES=$HOME/templates/

#
# Which commands.
#

# For Mac OSX: use gsed if available.
export SED=$(command -v gsed) || $(command -v sed)

# Default FZF preview mode (see tpl() and goto_project() in .bash/function)
export FZF_PREVIEW='fzf-tmux --multi --preview-window right:60% --preview'

export LANG="en_US.UTF-8"
