#!/usr/bin/env bash

#
# Bash functions
# self-written, copied, adapted...
# If not written myself, I probably took/stole/adapted it from
# Gary Bernhardt, Jan Moesen, Dave Lens, or some other dude(tte) on the web.
#


#
# Attach to an existing tmux session, create the session if it doesn't exist.
# If no session is given, create one based on the current working directory.
#
tmux_attach() {
    local project=$1
    local switch=""

    if [[ "$project" == "" ]]
    then
        project=${1-"$(basename "$PWD" | tr . -)"}
    fi

    # Depending on whether or not we are already in a tmux session (this is why
    # we check for $TMUX before it is created later on), we need to switch to
    # that session differently.
    if [[ "$TMUX" == "" ]]; then
        switch='tmux attach -t'
    else
        switch='tmux switch-client -t'
    fi

    tmux has-session -t "$project" > /dev/null 2>&1 || TMUX='' tmux new-session -s "$project" -d
    $switch "$project"
}


#
# Upload a screenshot to imgur "on the fly":
# Let user select region, take screenshot
# Upload screenshot to imgur.com
# Print resulting url to image.
#
# @see http://api.imgur.com/examples
#
imgur() {
    # API Key provided by Alan@imgur.com
    local api_key="b3625162d3418ac51a9ee805b1840452"
    local url_api_upload="http://api.imgur.com/2/upload.xml"
    local fn_image
    local response

    fn_image="/tmp/screenshot-$(date +%Y-%m-%d-%H-%M-%S).png"
    screencapture -ix "$fn_image"
    response=$(curl -s -F "image=@$fn_image" -F "key=$api_key" $url_api_upload)
    echo "$response" | tail -1 | $SED -E 's/.*<original>(.*)<\/original>.*/\1/'
}


#
# Create an SSH config host entry and add my public key to that host.
#
# @param The identifier to use for this SSH host configuration.
# @param The host name.
# @param The username for that host.
#
ssh_configure_host() {
    local identifier=$1
    local hostname=$2
    local username=$3

    if [[ "$identifier" == "" ]] || [[ "$username" == "" ]] || [[ "$hostname" == "" ]]
    then
        echo "usage: ssh_configure_host <identifier> <hostname> <username>"
    else
        echo -e "Host $identifier\n\tHostName $hostname\n\tUser $username\n\tIdentityFile ~/.ssh/id_rsa\n\tForwardAgent yes" >> ~/.ssh/config
        ssh "$identifier" 'mkdir -p .ssh && cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
        # TODO Use ssh_test_key()?
        tput bold; ssh -o PasswordAuthentication=no "$identifier" true && { tput setaf 2; echo 'Success!'; } || { tput setaf 1; echo 'Failure'; }; tput sgr0
        ssh_load_autocomplete
    fi
}


#
# adds ~/.ssh/config to the ssh autocomplete
# Call whenever ssh host config changes (@see ssh_configure_host)
#
ssh_load_autocomplete() {
    complete -W "$(awk '/^\s*Host\s*/ { sub(/^\s*Host /, ""); print; }' ~/.ssh/config)" ssh uli ssh_drush ssh_user
}


#
# Test a giveh ssh_config host identifier.
#
ssh_test_key() {
    local identifier=$1
    ssh -o PasswordAuthentication=no "$identifier" true && { tput setaf 2; echo 'Success!'; } || { tput setaf 1; echo 'Failure'; }; tput sgr0
}


#
# Put Tim Pope's sensible vimrc on a ssh-identified server.
#
ssh_install_default_vimrc() {
    local identifier=$1
    if [[ "$identifier" == "" ]]
    then
        echo "usage: ssh_install_default_vimrc <identifier>"
    else
        ssh "$identifier" 'curl https://raw.githubusercontent.com/tpope/vim-sensible/master/plugin/sensible.vim > ~/.vimrc'
    fi
}


#
# Return the user for a given SSH identifier.
#
ssh_user() {
    local sshidentifier=$1
    local hostregex

    hostregex=$(echo "$sshidentifier" | $SED -E 's/\./\\\./')
    echo $($SED -nE '/^\s*Host\s+'"$hostregex"'/,/^\s*User/p' ~/.ssh/config | grep User | $SED -E 's/^\s*User\s+//')
}


#
# Change to a project directory quickly, using FZF.
#
goto_project() {
    local project
    project=$(find $DIR_PROJECTS -type d -maxdepth 1 | cut -d/ -f5 | fzf)
    if [[ "$project" != "" ]]
    then
        cd "$DIR_PROJECTS"/"$project" || return
    fi
}


#
# Execute a drush command on a server via ssh
#
# @param The SSH identifier (as exported by domainator).
# @param The Drush command to execute on the server.
#
ssh_drush() {
    local sshidentifier=$1
    local drushcmd=$2
    local appname

    # Determine the name of the application, based on the ssh identifier.
    # The name of an application is max 14 chars.
    appname=$(echo "$sshidentifier" | $SED -E 's/\.(test|qa|prod)//')
    appname=${appname:0:14}

    ssh "$sshidentifier" 'cd apps/'"$appname"'/current && drush '"$drushcmd"''
}


#
# Shortcut for executing a `drush uli` on a server.
# uses ssh_drush()
#
# @param The SSH identifier (as exported by Domainator).
#
uli() {
    local sshidentifier=$1

    ssh_drush "$sshidentifier" uli
}

#
# Copy over a file from the template directory in the current directory.
# Use FZF to facilitate typing.
#
tpl() {
    local filename
    filename=$(find $DIR_TEMPLATES -type f | fzf)
    if [[ "$filename" != "" ]]
    then
        cp "$filename" ./
    fi
}
