#!/usr/bin/env bash

#
# Configure Bash prompt.
# Depends on .bash/colors
#


# GIT prompt configuration
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCOLORHINTS=1

# Thanks @janmoesen for pointing me to the \[\] surrounding the non-printing
# chars.  These are necessary to prevent issues with command line editing,
# -browsing, -completion.
PROMPT_COMMAND='__git_ps1 "\[${REVERSE}\] \w \[${NORMAL}\]" " [\$?]\n\[${REVERSE}\]   \[${NORMAL}\] "'
INITIAL_PROMPT_COMMAND=$PROMPT_COMMAND


#
# Simple prompt, mainly without fancy coloring and without git info.
# Useful when in a big directory: if you'd leave the git part on, the prompt
# will take _seconds_ before it appears.
#
prompt_simple() {
    PROMPT_COMMAND='PS1="\[${REVERSE}\] \w \[${NORMAL}\] [\$?]\n"'
}


#
# Restore the prompt back to its initial state.
#
prompt_restore() {
    PROMPT_COMMAND=$INITIAL_PROMPT_COMMAND
}
