# Simple format, for repositories that take more than half a second or so to
# Git status.
# format = "$directory$line_break$character"

add_newline = false

[character]
success_symbol = "[➜](bold cyan)"
error_symbol = ""

[status]
disabled = false
symbol = "✗"
format = "[$symbol $status](bold red)"
